run migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -176,28 +176,28 @@ jobs:
             cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml
 
-#   run-migrations:
-#     docker:
-#       # - image:
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Run migrations
-#           command: |
-  #            cd backend
-  #            npm install
-  #            Run and sve the migration output
-  #            npm run migrations > migrations_dump.txt
-             # exit 1
-#       - run:
-#           name: Send migration results to memstash
-#           command: |
-#              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-#              then
-#                curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-#              fi
-             # exit 1
-#      # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+#           run and sve the migration output
+            npm run migrations > migrations_dump.txt
+#           exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+             if grep -q "has been executed successfully." ~/cdond-c3-projectstarter/backend/migrations_dump.txt
+             then
+               curl -H "Content-Type: text/plain" -H "token: 638dca8a-6633-42fb-9162-44ee04dd0ea0" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+             fi
+#            exit 1
+#        Here's where you will add some code to rollback on failure      
 
 workflows:
   default:
@@ -219,5 +219,5 @@ workflows:
 #              only: [test-feature-branch]
       - configure-infrastructure:
            requires: [deploy-infrastructure]
-#     - run-migrations:
-  #         requires: [configure-infrastructure]
+      - run-migrations:
+           requires: [configure-infrastructure]
